### PR TITLE
ER Classifiers switched to SparseNetworkLBP

### LINKED ISSUE #327: Training SparseNetworkModels for ER
For implementing ER model in Saul-SL, it would be much more compact to stick to the same existing  EntityRelationClassifiers declarations. However, for SL, I use SparseNetworks rather than SparsePerceptrons. By changing EntityRelationClassifiers types, the ER Test Units fail to Load the trained SparsePerceptron models. So, it would be great if we train SparseNetworks also for ER and have them in the ER models Jar.

### PR DESCRIPTION
**Pull request by bhargav**
- Deployed new models and tested locally.
- Fixed #327 and #294

JointTraining was not updating weights when SparseNetworkLBP was used due to a stale reference to `network`. Updated the SparseNetworkLBP class to not store any values and interact with the actual class instead.

Changes in saul-core:
- Make the count variable an `AtomicInteger` instead of using `synchronized` to increment/decrement
- `addInstance` method has documentation and change in formatting. No functionality change.

### CODE REVIEW

File: saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/SparseNetworkLBP.scala [hunk 1]
```diff
@@ -5,20 +5,20 @@ import edu.illinois.cs.cogcomp.lbjava.learn.{ LinearThresholdUnit, SparseNetwork
...
+    * @param newVal
+    */
+  def iConjuctiveLables_=(newVal: Boolean): Unit = this.conjunctiveLabels = newVal
+
+  /** Override method to return LTU of type [[LinearThresholdUnit]].
+    * @param i Position of the LTU unit in the network.
+    * @return LTU unit of type [[LinearThresholdUnit]]
+    */
+  override def getLTU(i: Int): LinearThresholdUnit = super.getLTU(i).asInstanceOf[LinearThresholdUnit]
 }
```
Comment (danyaljj) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/SparseNetworkLBP.scala]: Would it make sense to remove this file and use the values directly?  We have access to all the possible parameters ...

File: saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala [hunk 2]
```diff
@@ -125,25 +126,32 @@ abstract class ConstrainedClassifier[T <: AnyRef, HEAD <: AnyRef](val onClassifi
...
-        pathToHead.get.to.getTestingInstances
+  private def deriveTestInstances: Iterable[T] = {
+    val dataNode: Option[Node[T]] = {
+      pathToHead match {
+        case Some(edge) => Some(edge.from)
+        case None =>
+          //  If pathToHead is not defined, try getting the node of onClassifier
+          onClassifier match {
+            case clf: Learnable[T] => Some(clf.node)
+            case _ => println("ERROR: pathToHead is not provided and the onClassifier is not a Learnable!"); None
```
Comment (danyaljj) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala]: logger.error?

Comment (danyaljj) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala]: and remove "ERROR: "

**Comment by danyaljj** [comment]
About the changes in results of L+I: I think the [existing evaluation](https://github.com/bhargav/saul/blob/1051b4a4bb196e082d33a89365e13e0f5d20f4e0/saul-examples/src/main/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/EntityRelation/EntityRelationApp.scala#L96-L97) is not quite correct.

Two scenarios: 
 - `constrainedClassifier.test(instanceCollection)`: it will evaluate over all the instances given in the input.  
 - `constrainedClassifier.test()`:  will collect all the instances [using `pathToHead`](https://github.com/bhargav/saul/blob/1051b4a4bb196e082d33a89365e13e0f5d20f4e0/saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala#L136); this doesn't always correspond to the instances we want/should test on. The whole point I was arguing in #294 is that we should never use `pathToHead` when it comes to evaluation (and it should be used only on the inference time). 

I don't remember how we reported the previous results in the readme file, but I think it was using the latter. I think we should update the results after [dropping `pathToHead` from testing](https://github.com/bhargav/saul/blob/1051b4a4bb196e082d33a89365e13e0f5d20f4e0/saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala#L136).

File: saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala (hunk 2 above)
Comment (bhargav) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala]: Fixed.

File: saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/SparseNetworkLBP.scala (hunk 1 above)
Comment (bhargav) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/SparseNetworkLBP.scala]: So, `this.conjunctiveLabels` boolean is protected in the base class and we are trying to set the value in the `JointTrainSparseNetworkLBP` methods. I removed other redundant methods.

**Comment by bhargav** [comment]
@danyaljj In the PR, `deriveTestInstances` method uses `pathToHead` to get the incident `Node` object. Once we have the node, I am using the `getTestingInstance` on the node to retrieve test candidates for the default `test()` method. Can you have a look at the latest iteration? I had already updated results after making those changes.

File: saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/SparseNetworkLBP.scala (hunk 1 above)
Comment (danyaljj) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/SparseNetworkLBP.scala]: Why not use this? https://github.com/IllinoisCogComp/lbjava/blob/master/lbjava/src/main/java/edu/illinois/cs/cogcomp/lbjava/learn/SparseNetworkLearner.java#L157

**Comment by danyaljj** [comment]
Oops. All looks good.

File: saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/SparseNetworkLBP.scala (hunk 1 above)
Comment (bhargav) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/SparseNetworkLBP.scala]: So that boolean does not have a public setter, hence we'll have to override it for now. Will see if it would make sense to move the weight update logic inside the LBJava SparseNetworkLearner class and call it directly.

Comment (danyaljj) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/SparseNetworkLBP.scala]: Correct. If you send a PR for it in lbjava, that'd be great.

**Comment by bhargav** [comment]
Updated LBJava Version and removed the `SparseNetworkLBP` file. Updated er-models package. But I see that some tests in POS and SRL are failing. Will investigate later.

**Comment by danyaljj** [comment]
Shoot this is a little sad ... the pre-trained models for SRL were trained on `SparseNetworkLBP ` and need to be retrained; @kordjamshidi how hard is re-training `predicateSenseClassifier ` and `argumentTypeLearner ` and `argumentXuIdentifierGivenApredicate `?

**Comment by bhargav** [comment]
Yeah. This might have to wait till next week then. I updated the ER Models but other examples need to be re-trained. 

@danyaljj Not sure why POS test is failing though.

**Comment by kordjamshidi** [comment]
Yes, this is what I mentioned before, we need to remove this class after the deadline.

**Comment by danyaljj** [comment]
@bhargav I think somehow the new lbjava version brings new version of Edison (which has had some changes) and causes some of the feature-extraction related stuff to fail (related to #339).

**Comment by bhargav** [comment]
@danyaljj @kordjamshidi Updated this PR. I'll have to train the SRL models again.

**Comment by kordjamshidi** [comment]
yes, it would be great to merge this one asap. @bhargav

**Comment by bhargav** [comment]
I tried running SRL training a couple of time and end up with Heap Size limit exceeded error while parsing data model. By the time 1k sentences were parsed, the process had used ~35Gb. Training examples have 37k sentences. I think we'll have to look at memory usage and fix issues there first.

**Comment by kordjamshidi** [comment]
You can look at it but I could run it by increasing the memory, using the instructions that I put here: 
https://github.com/IllinoisCogComp/saul/wiki/Common-Erros, maybe try this and see if it works for you.

**Comment by bhargav** [comment]
@danyaljj @kordjamshidi This is ready. The performance on SRL task was similar. It was less ( -0.5 %) on `aTr` but equal or better `bTr, cTr, dTr, fTr`.

**Comment by kordjamshidi** [comment]
ok, great.

File: saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala [hunk 3]
```diff
@@ -132,25 +132,28 @@ abstract class ConstrainedClassifier[T <: AnyRef, HEAD <: AnyRef](val onClassifi
       )(o.asInstanceOf[T])
   }
 
-  /** Test with given data, use internally
+  /** Derives Test Instances from the data model.
```
Comment (danyaljj) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala]: minor: `instances` lower case?

Comment (danyaljj) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala]: And do we always add `.` at the of comments?

File: saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala [hunk 4]
```diff
@@ -132,25 +132,28 @@ abstract class ConstrainedClassifier[T <: AnyRef, HEAD <: AnyRef](val onClassifi
...
+          case _ => logger.error("pathToHead is not provided and the onClassifier is not a Learnable!"); None
         }
-      } else {
-        pathToHead.get.to.getTestingInstances
-      }
-    }
-
-    val data: List[T] = allHeads.flatMap(getCandidates).toList.distinct
+      })
+      .map(node => node.getTestingInstances)
```
Comment (danyaljj) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala]: Minor: ` .map(_.getTestingInstances)`?

File: saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala [hunk 5]
```diff
@@ -132,25 +132,28 @@ abstract class ConstrainedClassifier[T <: AnyRef, HEAD <: AnyRef](val onClassifi
...
+  /** Derives Test Instances from the data model.
     *
-    * @return List of (label, (f1, precision, recall))
+    * @return Iterable of test instances for this classifier
     */
-  def test(): Results = {
-    val allHeads: Iterable[HEAD] = {
-      if (pathToHead.isEmpty) {
+  private def deriveTestInstances: Iterable[T] = {
+    pathToHead.map(edge => edge.from)
```
Comment (danyaljj) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala]: Minor: I usually would say `pathToHead.map(_.from)`, but now seems like keeping it this way would increase the readability.

File: saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala (hunk 4 above)
Comment (danyaljj) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala]: Same here: keeping it this way might increase readability.

File: saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/datamodel/node/Node.scala [hunk 6]
```diff
@@ -85,42 +87,47 @@ class Node[T <: AnyRef](val keyFunc: T => Any = (x: T) => x, val tag: ClassTag[T
...
+    this.collection.add(nodeInstance)
+    this.orderingMap.put(order, nodeInstance)
+    this.reverseOrderingMap.put(nodeInstance, order)
+
+    if (populateEdge) {
+      outgoing.foreach(_.populateUsingFrom(instance, train))
+      incoming.foreach(_.populateUsingTo(instance, train))
+    }
+
+    joinNodes.foreach(_.addFromChild(this, instance, train, populateEdge))
```
Comment (danyaljj) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/datamodel/node/Node.scala]: Could you document the observation that this line takes too much time?

File: saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/datamodel/node/Node.scala [hunk 7]
```diff
@@ -85,42 +87,47 @@ class Node[T <: AnyRef](val keyFunc: T => Any = (x: T) => x, val tag: ClassTag[T
...
+    * @param train If the instance is a training instance.
+    * @param populateEdge If populating edges from the current Node.
+    */
+  def addInstance(instance: T, train: Boolean = true, populateEdge: Boolean = true): Unit = {
+    val nodeInstance = toNT(instance)
+
+    if (containsNT(nodeInstance)) {
+      //       logger.warn(s"The instance $t is duplicate and it will be ignored! " +
+      //         s"This might be because you add the same instance to both train and test set. ")
+      return
```
Comment (danyaljj) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/datamodel/node/Node.scala]: [Some scala programmer will curse you](https://tpolecat.github.io/2014/05/09/return.html) one day for this.

File: saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/datamodel/node/Node.scala [hunk 8]
```diff
@@ -275,7 +282,7 @@ class Node[T <: AnyRef](val keyFunc: T => Any = (x: T) => x, val tag: ClassTag[T
   }
 
   def loadDerivedInstances(in: ExceptionlessInputStream) = {
-    count = in.readInt()
+    count = new AtomicInteger(in.readInt())
```
Comment (danyaljj) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/datamodel/node/Node.scala]: Something to remember for future: replacing may of our integers/counters with `AtomicInteger` might be a good idea.

File: saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/datamodel/node/Node.scala [hunk 9]
```diff
@@ -290,10 +297,9 @@ class Node[T <: AnyRef](val keyFunc: T => Any = (x: T) => x, val tag: ClassTag[T
   final val propertyCacheList = new ListBuffer[MutableHashMap[_, Any]]()
 
   def clearPropertyCache(): Unit = {
-    if (propertyCacheList nonEmpty) {
+    if (propertyCacheList.nonEmpty) {
```
Comment (danyaljj) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/datamodel/node/Node.scala]: 👍

File: saul-examples/src/test/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/SemanticRoleLabeling/ModelsTest.scala [hunk 10]
```diff
@@ -15,15 +15,17 @@ class ModelsTest extends FlatSpec with Matchers {
...
-    }
+    results.perLabel
+      .filter(!_.f1.isNaN)
+      .foreach {
+        result =>
+          result.label match {
+            case "A0" => (result.f1 >= 0.9) should be(true)
+            case "A1" => (result.f1 >= 0.9) should be(true)
+            case "A2" => (result.f1 >= 0.6) should be(true)
+            case _ => (result.f1 >= 0.0) should be(true)
```
Comment (danyaljj) [inline saul-examples/src/test/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/SemanticRoleLabeling/ModelsTest.scala]: could you [add upperbound](https://github.com/IllinoisCogComp/saul/blob/master/saul-examples/src/test/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/POSTagger/POSTaggerTest.scala#L135) to these F-scores?

**Comment by danyaljj** [comment]
Just a few comments. Feel free to merge after addressing them.

File: saul-examples/src/test/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/SemanticRoleLabeling/ModelsTest.scala (hunk 10 above)
Comment (bhargav) [inline saul-examples/src/test/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/SemanticRoleLabeling/ModelsTest.scala]: Updated.

File: saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala (hunk 3 above)
Comment (bhargav) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/classifier/ConstrainedClassifier.scala]: Updated. We do have `.` at the end of some comments. No strict style guide though.

File: saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/datamodel/node/Node.scala (hunk 7 above)
Comment (bhargav) [inline saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/datamodel/node/Node.scala]: Removed the `return` statement and make it `logger.trace`. I do not mind having an `else` statement here as the lines are not too long to cause indent issues.

File: saul-examples/src/test/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/SemanticRoleLabeling/ModelsTest.scala [hunk 11]
```diff
@@ -78,11 +80,11 @@ class ModelsTest extends FlatSpec with Matchers {
...
     results.perLabel.foreach {
-      case result =>
+      result =>
         result.label match {
-          case "A0" => (result.f1 >= 0.9) should be(true)
-          case "A1" => (result.f1 >= 0.9) should be(true)
-          case "A2" => (result.f1 >= 0.6) should be(true)
+          case "A0" => result.f1 should be(0.95 +- 0.05)
+          case "A1" => result.f1 should be(0.95 +- 0.05)
+          case "A2" => result.f1 should be(0.8 +- 0.2)
```
Comment (danyaljj) [inline saul-examples/src/test/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/SemanticRoleLabeling/ModelsTest.scala]: lol this bounds are super-big! could you bring then in the margin of `0.02`?

File: saul-examples/src/test/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/SemanticRoleLabeling/ModelsTest.scala [hunk 12]
```diff
@@ -15,23 +15,25 @@ class ModelsTest extends FlatSpec with Matchers {
...
   }
 
   "predicate identifier (dTr)" should "perform higher than 0.98." in {
     ClassifierUtils.LoadClassifier(SRLConfigurator.SRL_JAR_MODEL_PATH.value + "/models_dTr/", predicateClassifier)
     val results = predicateClassifier.test()
     results.perLabel.foreach {
-      case result =>
-        result.label match { case "true" => (result.f1 >= 0.98) should be(true) }
+      result =>
+        result.label match { case "true" => result.f1 should be(0.99 +- 0.01) }
```
Comment (danyaljj) [inline saul-examples/src/test/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/SemanticRoleLabeling/ModelsTest.scala]: coolio!

File: saul-examples/src/test/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/SemanticRoleLabeling/ModelsTest.scala [hunk 13]
```diff
@@ -15,23 +15,25 @@ class ModelsTest extends FlatSpec with Matchers {
...
-    }
+    results.perLabel
+      .filter(!_.f1.isNaN)
+      .foreach {
+        result =>
+          result.label match {
+            case "A0" => result.f1 should be(0.95 +- 0.05)
+            case "A1" => result.f1 should be(0.95 +- 0.05)
+            case "A2" => result.f1 should be(0.8 +- 0.2)
+            case _ => (result.f1 >= 0.0) should be(true)
```
Comment (danyaljj) [inline saul-examples/src/test/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/SemanticRoleLabeling/ModelsTest.scala]: Same here: decrease the error margin to `0.02`?

**Comment by danyaljj** [comment]
Small comment on the test error margin. Otherwise good to merge.

**Comment by bhargav** [comment]
Updated test margins. :)

**Comment by danyaljj** [comment]
Looks good. Merging!
